function collectFigsToPDF(myDB,fig_name)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% cycles through database DB, looks for a figure named fig_name and appends
% it to a powerpoint file with name [fig_name]_all_sessions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

close all;
for i = 1:length(myDB)
    goto(myDB{i});
    fff = imread([fig_name,'.jpg']);
    figure;
    imshow(fff,'InitialMagnification',100);
end

pptx    = exportToPPTX('', ...
    'Dimensions',[10 8], ...
    'Title','Example Presentation', ...
    'Author','MATLAB', ...
    'Subject','Automatically generated PPTX file', ...
    'Comments','This file has been automatically generated by exportToPPTX');
% Another way of setting some properties
pptx.title          = 'Demonstration Presentation';
pptx.author         = 'exportToPPTX Example';
pptx.subject        = 'Demonstration of various exportToPPTX commands';
pptx.description    = 'Description goes in here';
% Additionally background color for all slides can be set as follows:
% exportToPPTX('new','BackgroundColor',[0.5 0.5 0.5]);
% Add some slides
%figH = figure('Renderer','zbuffer'); mesh(peaks); view(0,0);
hdl = findall(groot,'Type','figure')

for islide=1:length(hdl),
    slideId = pptx.addSlide();
    fprintf('Added slide %d\n',slideId);
    pptx.addPicture(hdl(i));
    %pptx.addTextbox(sprintf('Slide Number %d',slideId));
    %pptx.addNote(sprintf('Notes data: slide number %d',slideId));
    
    % Rotate mesh on each slide
%     view(18*islide,18*islide);
end
close(hdl);
% Check current presentation
fprintf('Presentation size: %f x %f\n',pptx.dimensions);
fprintf('Number of slides: %d\n',pptx.numSlides);
% Save presentation and close presentation -- overwrite file if it already exists
% Filename automatically checked for proper extension
newFile     = pptx.save(['/storage2/perentos/data/recordings/',fig_name,'_all_sessions']);